"""Here data imports from the file '.env' of django project"""

import os

import dotenv

dotenv.load_dotenv()

PROJECT_REFERRAL_SETTING_POSTGRES_DB = os.getenv(
    "PROJECT_REFERRAL_SETTING_POSTGRES_DB", ""
)
PROJECT_REFERRAL_SETTING_POSTGRES_USER = os.getenv(
    "PROJECT_REFERRAL_SETTING_POSTGRES_USER", ""
)
PROJECT_REFERRAL_SETTING_POSTGRES_PASSWORD = os.getenv(
    "PROJECT_REFERRAL_SETTING_POSTGRES_PASSWORD", ""
)
PROJECT_REFERRAL_SETTING_POSTGRES_HOST = os.getenv(
    "PROJECT_REFERRAL_SETTING_POSTGRES_HOST", ""
)
PROJECT_REFERRAL_SETTING_POSTGRES_PORT = os.getenv(
    "PROJECT_REFERRAL_SETTING_POSTGRES_PORT", ""
)